---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-prometheus-monitoring
  namespace: openshift-operators
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - configmaps